version: "3.8"

services:
  backend:
    image: "711387105994.dkr.ecr.ap-northeast-2.amazonaws.com/ourhood-server:latest"
    container_name: ourhood-server
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./private_key.pem:/private_key.pem

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    network_mode: "host"
    volumes:
      - ./redis-data:/data

  nginx:
    image: "nginx:alpine"
    container_name: nginx
    environment:
      - TZ=Asia/Seoul
    network_mode: "host"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
