services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: ourhood-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - redis_network
    volumes:
      - ./private_key.pem:/private_key.pem

  redis:
    image: "redis:alpine"
    container_name: redis
    environment:
      - TZ=Asia/Seoul
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    networks:
      - redis_network

  nginx:
    image: "nginx:alpine"
    container_name: nginx
    environment:
      - TZ=Asia/Seoul
    network_mode: "host"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx

volumes:
  redis_volume: # 볼륨 정의

networks:
  redis_network: # 네트워크 정의
    driver: bridge