spring:
  config:
    activate:
      on-profile: "cloud"
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET}
    cloudfront:
      private-key-path: ${CLOUDFRONT_PRIVATE_KEY_PATH}
      key-pair-id: ${CLOUDFRONT_KEY_PAIR_ID}
      custom-domain: ${CLOUDFRONT_CUSTOM_DOMAIN}
      service-domain: ${CLOUDFRONT_SERVICE_DOMAIN}