spring:
  profiles:
    active: local
    group:
      local: "local, datasource"
      dev: "dev, datasource"
      prod: "prod, datasource"
    include:
      - redis
      - security
      - cloud
  jpa:
    open-in-view: false
