spring:
  jpa:
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    url:
      auth-code-url: https://kauth.kakao.com/oauth/authorize
      token-url: https://kauth.kakao.com/oauth/token
      user-info-url: https://kapi.kakao.com/v2/user/me

auth:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}

cookie:
  refresh-token:
    expiry: ${COOKIE_REFRESH_TOKEN_EXPIRY}
    name: "refresh_token"

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${S3_BUCKET}
    cloudfront:
      distribution-domain: ${CLOUDFRONT_DISTRIBUTION_DOMAIN}
      private-key-path: ${CLOUDFRONT_PRIVATE_KEY_PATH}
      key-pair-id: ${CLOUDFRONT_KEY_PAIR_ID}
      base-url: ${CLOUDFRONT_BASE_URL}